# Generated by Django 3.1.4 on 2021-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='access_rights',
            field=models.ManyToManyField(blank=True, help_text='Wähle Räumlichkeiten aus, die mit diesem Schküssel zugänglich sind', to='equipment.Room'),
        ),
    ]
