# Generated by Django 3.1.2 on 2020-10-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    def populate_fitness_level(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        FitnessLevel = apps.get_model('fitness', 'FitnessLevel')
        FitnessLevel.objects.using(db_alias).create(name="G26.3")
        FitnessLevel.objects.using(db_alias).create(name="G26.2")

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_fitness_level),
    ]
