# Generated by Django 3.1.4 on 2021-06-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0002_populate_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='expiration_date',
            field=models.DateField(verbose_name='Ablaufdatum'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='firefighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Einsatzkraft'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='issue_date',
            field=models.DateField(verbose_name='Ausstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.fitnesslevel', verbose_name='Art der Tauglichkeit'),
        ),
    ]
