# Generated by Django 3.1.2 on 2020-10-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    def populate_authorities(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Authority = apps.get_model('personal_data', 'Authority')
        Authority.objects.using(db_alias).create(name="Landeshauptstadt Potsdam")
        Authority.objects.using(db_alias).create(name="Berlin")
        Authority.objects.using(db_alias).create(name="Land Brandenburg - LSTE")

    def populate_category_of_driver_license(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        CategoryOfDriverLicense = apps.get_model('personal_data', 'CategoryOfDriverLicense')
        CategoryOfDriverLicense.objects.using(db_alias).create(name="B")
        CategoryOfDriverLicense.objects.using(db_alias).create(name="BE")
        CategoryOfDriverLicense.objects.using(db_alias).create(name="C")
        CategoryOfDriverLicense.objects.using(db_alias).create(name="C1")
        CategoryOfDriverLicense.objects.using(db_alias).create(name="CE")

    def populate_rank_brandenburg(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Rank = apps.get_model('personal_data', 'Rank')
        Rank.objects.using(db_alias).create(sorting_order=1, name="Feuerwehrmann/-frau-Anwärter/-in")
        Rank.objects.using(db_alias).create(sorting_order=2, name="Feuerwehrmann/-frau")
        Rank.objects.using(db_alias).create(sorting_order=3, name="Oberfeuerwehrmann/-frau")
        Rank.objects.using(db_alias).create(sorting_order=4, name="Hauptfeuerwehrmann/-frau")
        Rank.objects.using(db_alias).create(sorting_order=5, name="Löschmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=6, name="Oberlöschmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=7, name="Hauptlöschmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=8, name="Erste/r Hauptlöschmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=9, name="Brandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=10, name="Oberbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=11, name="Hauptbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=12, name="Erste/r Hauptbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=13, name="Gemeinde-/Stadt-/Amtsbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=14, name="Stellv. Kreisbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=15, name="Kreisbrandmeister/-in")
        Rank.objects.using(db_alias).create(sorting_order=16, name="Stellv. Landesbreanddirektor/-in")
        Rank.objects.using(db_alias).create(sorting_order=17, name="Landesbreanddirektor/-in")

    def populate_user_status(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        UserStatus = apps.get_model('personal_data', 'UserStatus')
        UserStatus.objects.using(db_alias).create(name="Aktiv", active=True)
        UserStatus.objects.using(db_alias).create(name="Pausiert", active=False)
        UserStatus.objects.using(db_alias).create(name="Ausgetreten", active=False)

    def populate_honor(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Honor = apps.get_model('personal_data', 'Honor')
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Kupfer",
                                             sorting_order=1)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Bronze",
                                             sorting_order=2)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Silber",
                                             sorting_order=3)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Gold 40",
                                             sorting_order=4)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Gold 50",
                                             sorting_order=5)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Gold 60",
                                             sorting_order=6)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Gold 70",
                                             sorting_order=7)
        Honor.objects.using(db_alias).create(name="Medaille für Treue Dienste in der Freiwilligen Feuerwehr in Gold 75",
                                             sorting_order=8)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Brandschutz (Brandenburg) in Silber am Bande",
                                             sorting_order=9)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Brandschutz (Brandenburg) in Gold am Bande",
                                             sorting_order=10)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Brandschutz (Brandenburg) in Gold als Sonderstufe",
                                             sorting_order=11)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Katastrophenschutz (Brandenburg) in Silber am Bande",
                                             sorting_order=12)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Katastrophenschutz (Brandenburg) in Gold am Bande",
                                             sorting_order=13)
        Honor.objects.using(db_alias).create(name="Ehrenzeichen im Katastrophenschutz (Brandenburg) in Gold als Sonderstufe",
                                             sorting_order=14)
        Honor.objects.using(db_alias).create(name="Feuerwehr-Leistungsabzeichen in Bronze, Brandenburg",
                                             sorting_order=15)
        Honor.objects.using(db_alias).create(name="Feuerwehr-Leistungsabzeichen in Silber, Brandenburg",
                                             sorting_order=16)
        Honor.objects.using(db_alias).create(name="Feuerwehr-Leistungsabzeichen in Gold, Brandenburg",
                                             sorting_order=17)
        Honor.objects.using(db_alias).create(name="Feuerwehr-Leistungsabzeichen in Gold (Sonderstufe), Brandenburg",
                                             sorting_order=18)
        Honor.objects.using(db_alias).create(
            name="Feuerwehr-Leistungsabzeichen für technische Hilfe in Bronze, Brandenburg", sorting_order=19)
        Honor.objects.using(db_alias).create(
            name="Feuerwehr-Leistungsabzeichen für technische Hilfe in Silber, Brandenburg", sorting_order=20)
        Honor.objects.using(db_alias).create(
            ame="Feuerwehr-Leistungsabzeichen für technische Hilfe in Gold, Brandenburg", sorting_order=21)
        Honor.objects.using(db_alias).create(
            name="Feuerwehr-Leistungsabzeichen für technische Hilfe in Gold (Sonderstufe), Brandenburg",
            sorting_order=22)
        Honor.objects.using(db_alias).create(name="Medaille \"Oderflut 1997\", Brandenburg", sorting_order=23)
        Honor.objects.using(db_alias).create(name="Medaille \"Elbflut 2002\", Brandenburg", sorting_order=24)
        Honor.objects.using(db_alias).create(name="Medaille \"Waldbrand 1992\", Brandenburg", sorting_order=25)
        Honor.objects.using(db_alias).create(name="Medaille \"Hochwasser 2013\", Brandenburg", sorting_order=26)
        Honor.objects.using(db_alias).create(name="Brandenburgische Rettungsmedaille", sorting_order=27)
        Honor.objects.using(db_alias).create(name="Verdienstorden des Landes Brandenburg", sorting_order=28)
        Honor.objects.using(db_alias).create(
            name="Medaille des Landtags von Brandenburg zur Anerkennung von Verdiensten für das Gemeinwesen",
            sorting_order=29)

    def populate_role(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Role = apps.get_model('personal_data', 'Role')
        Role.objects.using(db_alias).create(name="Ortswehrführer/-in", sorting_order=1)
        Role.objects.using(db_alias).create(name="Stellv. Ortswehrführer/-in", sorting_order=2)
        Role.objects.using(db_alias).create(name="Jugendwart/-in", sorting_order=3)
        Role.objects.using(db_alias).create(name="Stellv. Jugendwart/-in", sorting_order=4)
        Role.objects.using(db_alias).create(name="Gemeinde-, Stadt-, Amtswehrführer/-in", sorting_order=5)
        Role.objects.using(db_alias).create(name="Stellv. Gemeinde-, Stadt-, Amtswehrführer/-in", sorting_order=6)
        Role.objects.using(db_alias).create(name="Wehrsprecher/-in", sorting_order=7)
        Role.objects.using(db_alias).create(name="Stellv. Wehrsprecher/-in", sorting_order=8)
        Role.objects.using(db_alias).create(name="Stellv. Gemeinde-, Stadt-, Amtswehrführer/-in", sorting_order=9)
        Role.objects.using(db_alias).create(name="Kreisbrandmeister/-in", sorting_order=10)
        Role.objects.using(db_alias).create(name="Stellv. Kreisbrandmeister/-in", sorting_order=11)
        Role.objects.using(db_alias).create(name="Landesbranddirektor/-in", sorting_order=12)
        Role.objects.using(db_alias).create(name="Stellv. Landesbranddirektor/-in", sorting_order=13)

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_authorities),
        migrations.RunPython(populate_category_of_driver_license),
        migrations.RunPython(populate_rank_brandenburg),
        migrations.RunPython(populate_user_status),
        migrations.RunPython(populate_honor),
        migrations.RunPython(populate_role),
    ]
