# Generated by Django 3.1.2 on 2020-11-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_populate_default_data_brandenburg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
