# Generated by Django 3.1.4 on 2021-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_populate_default_data_brandenburg'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighter',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/None/no-img.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
