# Generated by Django 3.1.4 on 2020-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_delete_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firefighter',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('view_all', 'Get an overview of all firefighters'), ('view_detail', 'Get detailed information about a firefighter')]},
        ),
        migrations.AlterField(
            model_name='firefighter',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='firefighter',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Nachname'),
        ),
    ]
