# Generated by Django 3.1.2 on 2020-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
        ('fitness', '0001_initial'),
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Specify admission restrictions', to='qualification.CourseRequirement'),
        ),
    ]
