# Generated by Django 3.1.2 on 2020-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_delete_event'),
        ('fitness', '0002_populate_default_data'),
        ('qualification', '0002_populate_default_data_brandenburg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license_requirement', models.ManyToManyField(blank=True, help_text='Select driver license categories that each individually satisfy this requirement.', to='personal_data.CategoryOfDriverLicense')),
                ('fitness_requirement', models.ManyToManyField(blank=True, help_text='Select fitness levels that each individually satisfy this requirement.', to='fitness.FitnessLevel')),
                ('qualification_requirement', models.ManyToManyField(blank=True, help_text='Select courses that each individuallysatisfy this requirement.', to='qualification.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Specify admission restrictions', to='qualification.CourseRequirement'),
        ),
    ]
