# Generated by Django 3.1.4 on 2020-12-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_auto_20201101_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={},
        ),
    ]
