# Generated by Django 3.1.4 on 2021-06-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendees',
            field=models.ManyToManyField(help_text='Select all attendees of this event', related_name='attendee', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end',
            field=models.DateTimeField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='person_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start',
            field=models.DateTimeField(verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='code_word',
            field=models.CharField(choices=[('bkl', 'B:Klein'), ('bpkw', 'B:PKW'), ('blkw', 'B:LKW'), ('bss', 'B:Schornstein'), ('bgk', 'B:Gebäude klein'), ('bgg', 'B:Gebäude groß'), ('bso', 'B:Sonderobjekt'), ('bbma', 'B:BMA'), ('bfl', 'B:Fläche'), ('bw', 'B:Wald'), ('bwg', 'B:Wald groß'), ('bschiene', 'B:Schiene'), ('bb', 'B:Boot'), ('bschiff', 'B:Schiff'), ('bkf', 'B:Kleinflugzeug'), ('bgf', 'B:Großflugzeug'), ('bex', 'B:Explosion'), ('hkl', 'H:Klein'), ('hnat', 'H:Natur'), ('hhilf', 'H:Hilfeleistung'), ('htuer', 'H:Türnotöffnung'), ('hvuop', 'H:VU ohne P'), ('hvump', 'H:VU mit P'), ('hvukl', 'H:VU Klemm'), ('hvulkw', 'H:VU LKW/Bus'), ('hvuschiene', 'H:VU Schiene'), ('hvuschiff', 'H:VU Schiff'), ('hflk', 'H:Flugzeugunfall klein'), ('hflg', 'H:Flugzeugunfall groß'), ('hps', 'H:Person auf Schiene'), ('hpw', 'H:Person im Wasser/Eis'), ('hrht', 'H:Rettung aus Höhen/Tiefen'), ('hg', 'H:Gas'), ('hgkl', 'H:Gefahrgut klein'), ('hggr', 'H:Gefahrgut groß'), ('he', 'H:Einsturz'), ('hoell', 'H:ÖL Land'), ('hoelw', 'H:ÖL auf Wasser'), ('htin', 'H:Tier in Not'), ('hkom', 'H:Kommunal'), ('htmr', 'H:Person-TMR')], max_length=10, verbose_name='Stichwort'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_id',
            field=models.IntegerField(verbose_name='Einsatznummer'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bezeichnung des Dienstes'),
        ),
    ]
