# Generated by Django 3.1.4 on 2020-12-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201101_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('view_all', 'Get an overview of all firefighters')]},
        ),
    ]
