# Generated by Django 3.1.4 on 2021-10-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210613_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('view_all_attendance', 'Get an overview of all attendances'), ('create_confirmation', "Create a confirmation letter to attest a firefighter's attendance in an operation")]},
        ),
    ]
